### ISSUE TITLE
Next major release of MeteoalarmCard

### ISSUE THREAD

**Issue by MrBartusek** [MrBartusek/MeteoalarmCard#82]
Hey! I'm currently working on version `v2.0.0` on the new branch [`2.0`](https://github.com/MrBartusek/MeteoalarmCard/tree/2.0) More info about why this this decision was taken, will be clarified in the release notes. In short, some stuff needs to be removed and rethought. That, will bring breaking changes. I will finally work on the ability to work with multiple entities for  #67  and #71. After [almost a year!](https://github.com/MrBartusek/MeteoalarmCard/releases/tag/v1.0.0) of piling up code, it became a bit messy so it's in desperate need of cleanup. Part of that cleanup will be rewriting it to match https://github.com/custom-cards/boilerplate-card style of the project and thus, switching to Typescript!

**TASK LIST FOR 2.0:**

Features
- [x] Rewrite to Typescript and base the code on https://github.com/custom-cards/boilerplate-card
- [x] Rewamp the visual editor
- [x] Add support for multiple entities
- [x] DWD: indicate which sensor is used
- [x] Add an slider for displaying more than one alert
- [x] Make slider optional

New integrations
- #71
- #77
- #67
- #78

Bugs
- #81
- #83
